import configparser

config = configparser.ConfigParser()
config.read('data.ini', encoding="utf-8")

START_URL = config.get('DEFAULT', 'START_URL')
ELEMENT_LOAD_SECONDS = config.get('DEFAULT', 'ELEMENT_LOAD_SECONDS')
MANAGER_NAME = config.get('DEFAULT', 'MANAGER_NAME')
MANAGER_PASS = config.get('DEFAULT', 'MANAGER_PASS')
NAME = config.get('DEFAULT', 'NAME')
USER_NAME = config.get('DEFAULT', 'USER_NAME')
USER_PASS = config.get('DEFAULT', 'USER_PASS')
AVATAR = config.get('DEFAULT', 'AVATAR')
BIRTHDAY = config.get('DEFAULT', 'BIRTHDAY')
DATE_START = config.get('DEFAULT', 'DATE_START')
HOBBY = config.get('DEFAULT', 'HOBBY')
NAME1 = config.get('DEFAULT', 'NAME1')
SURNAME1 = config.get('DEFAULT', 'SURNAME1')
FATHERNAME = config.get('DEFAULT', 'FATHERNAME')
CAT = config.get('DEFAULT', 'CAT')
DOG = config.get('DEFAULT', 'DOG')
PARROT = config.get('DEFAULT', 'PARROT')
CAVY = config.get('DEFAULT', 'CAVY')
HAMSTER = config.get('DEFAULT', 'HAMSTER')
SQUIRREL = config.get('DEFAULT', 'SQUIRREL')
PHONE = config.get('DEFAULT', 'PHONE')
ADDRESS = config.get('DEFAULT', 'ADDRESS')
INN = config.get('DEFAULT', 'INN')
